version: "3.1"
services:
  api-t2:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "npm install && adonis serve --dev"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
    depends_on:
      - mongo
  mongo: 
    image: mongo:4.2-bionic
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=bdmongo
    volumes:
      - ../mongodb/:/data/db
    ports:
      - 27017:27017     